services:
  dev:
    build: .
    ports:
      - "8000:8000"  # Expose dev server port
    volumes:
      - .:/app  # Mount current directory into the container
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
    command: npm run dev # Copy assets and start dev server
    working_dir: /app  # Ensure the working directory is set properly
